---
# tasks file for postgresql
#
- name: Install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Ensuring all PostgreSQL pkgs are installed
  yum:
    name:
      - postgresql10-server
      - postgresql10-devel
      - postgresql10-contrib
      - postgresql10-plpython
      - python-psycopg2
    state: present

- name: Initialize postgres if necessary
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  args:
    creates: /var/lib/pgsql/10/data/postgresql.conf

- name: Distribute Postgresql config files
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/pgsql/10/data/{{ item }}"
    mode: 0600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify:
    - restart_postgresql

- name: Ensuring postgresql is started and enabled
  service:
    name: postgresql-10.service
    state: started
    enabled: True

- name: Creating Users if not empty list
  postgresql_user:
    name: odoo
    password: password
    role_attr_flags: "NOCREATEDB,NOSUPERUSER,NOCREATEROLE"
  become_user: postgres

- name: Creating Postgresql Databases
  postgresql_db:
    name: db
    owner: odoo
    encoding: UTF-8
  become_user: postgres

- name: Granting DB rights to identified user
  postgresql_user:
    name: odoo
    password: password
    role_attr_flags: "NOCREATEDB,NOSUPERUSER,NOCREATEROLE"
    db: db
    priv: 'ALL'
  become_user: postgres
