---
# tasks file for postgresql
#
- name: Install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Ensuring all PostgreSQL pkgs are installed
  yum:
    name:
      - postgresql10-server
      - postgresql10-devel
      - postgresql10-contrib
      - postgresql10-plpython
      - python-psycopg2
    state: present

- name: Initialize postgres if necessary
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  args:
    creates: /var/lib/pgsql/10/data/postgresql.conf

- name: Distribute Postgresql config files
  template:
    src: "{{ item }}.j2"
    dest: "/var/lib/pgsql/10/data/{{ item }}"
    mode: 0600
  with_items:
    - postgresql.conf
    - pg_hba.conf
  notify:
    - restart_postgresql

- name: Ensuring postgresql is started and enabled
  service:
    name: postgresql-10.service
    state: started
    enabled: True

- name: Creating Users if not empty list
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "NOCREATEDB,NOSUPERUSER,NOCREATEROLE"
  become_user: postgres
  with_items: "{{ pgsql_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Creating Postgresql Databases
  postgresql_db: 
    name: "{{ item.name }}" 
    owner: "{{ item.owner }}" 
    encoding: UTF-8
  become_user: postgres
  with_items: "{{ pgsql_databases }}"
  loop_control:
    label: "{{ item.name }}"

- name: Granting DB rights to identified user
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "NOCREATEDB,NOSUPERUSER,NOCREATEROLE"
    db: "{{ item.db }}"
    priv: 'ALL'
  become_user: postgres
  with_items: "{{ pgsql_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Opening up postgresql tcp port
  include_role:
    name: iptables
    tasks_from: custom-policy
  vars:
    iptables_policy_name: "postgresql-{{ item | replace('/','-') }}"
    iptables_protocol: tcp
    iptables_port: "5432"
    iptables_source: "{{ item }}"
  when: pgsql_network_listen
  with_items: "{{ pgsql_network_subnets }}"
  tags:
    - iptables
# Backup
- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client
